language: cpp

compiler:
  - gcc
#  - clang

before_install:
  - sudo apt-get update

install:
 # gtest
 - sudo apt-get install libgtest-dev
 - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

 #coveralls
 - sudo pip install cpp-coveralls --use-mirrors
 
script:
  - g++ -fprofile-arcs -ftest-coverage src/PopCount.cpp src/SequenceAlignmentBitParallel.cpp test/SequenceAlignmentBitParallelTest.cpp -lgtest -lgtest_main -lpthread -o SequenceAlignmentBitParallel_test
  - ./SequenceAlignmentBitParallel_test

after_success:
  - coveralls --exclude src

branches:
  only:
    - master

notifications:
  email: false
